name: Lighthouse
on: [push, pull_request]
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm ci && npm install -g @lhci/cli@0.7.x
      - run: npm run build
      - run: lhci autorun
